package com.xiaoyan.railway.order;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Order entity mapped to the {@code orders} table.
 * Column names are snake_case; MyBatis-Plus maps them to these camelCase fields automatically.
 *
 * <p>Lombok generates the accessors and the builder; {@code @NoArgsConstructor} is required by
 * MyBatis-Plus reflection, {@code @AllArgsConstructor} is consumed by {@code @Builder}.
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@TableName("orders")
public class Order {
    /** ID is generated by {@link OrderIdGenerator}, not auto-increment. */
    @TableId(value = "id", type = IdType.INPUT)
    private Long id;
    private String orderNo;
    private Long userId;
    private Long trainRunId;
    private Long fromStationId;
    private Long toStationId;
    /** Segment-lock info needed to release Redis inventory on cancel/refund. */
    private Long seatTypeId;
    private Integer fromSeq;
    private Integer toSeq;
    private Integer quantity;
    private Integer orderStatus;
    private BigDecimal totalAmount;
    private LocalDateTime expireAt;
    private String idempotencyKey;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
